server:
  port: 8300
spring:
  application:
    name: school-acs-server
  ### 配置 zipkin 服务的地址
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      ### 配置 sleuth 的请求抽样比例，推送给 Zipkin。分为：抽样收集和每个请求都收集。默认：0.1，收集 1/10 请求作为样本。1.0-收集全部请求
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ribbon:
  ###创建连接超时时间，默认：1s，单位：ms。
  ConnectTimeout: 5000
  ###创建连接后从服务器读取到可用资源所用的时间，默认：1s，单位：ms。
  ReadTimeout: 5000

### 默认值：false-未开启。feign 开启请求熔断，未开启，只会报 Socket 超时错误，不会执行降级方法
feign:
  hystrix:
    enabled: true

