server:
  port: 8500
spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8000/eureka/,http://${eureka.instance.ip-address}:8001/eureka/,http://${eureka.instance.ip-address}:8002/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

app:
  ### portal 中新建 Application 的 AppId
  id: zuul_server_config
apollo:
  ### configserver 的地址
  meta: http://${configserver.host}:8080

### 配置网关反向代理
#zuul:
#  routes:
#    ### 定义转发规则。这个规则名称可以随意命名
#    api-a:
#      ### 以 /api-member/ 访问转发到会员服务
#      path: /api-member/**
#      ### 服务名称。Zuul 网关默认整合了 ribbon，ribbon + serverId 实现本地负载均衡方式调用接口
#      serviceId: member-server
#    api-b:
#      path: /api-order/**
#      serviceId: order-server