server:
  port: 8500
spring:
  application:
    name: zuul-server
  ### 配置 zipkin 服务的地址
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      ### 配置 sleuth 的请求抽样比例，推送给 Zipkin。分为：抽样收集和每个请求都收集。默认：0.1，收集 1/10 请求作为样本。1.0-收集全部请求
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

app:
  ### portal 中新建 Application 的 AppId
  id: zuul_server_config
apollo:
  ### configserver 的地址
  meta: http://${configserver.host}:8080

### 配置网关反向代理
#zuul:
#  routes:
#    ### 定义转发规则。这个规则名称可以随意命名
#    api-a:
#      ### 以 /api-member/ 访问转发到会员服务
#      path: /api-basic/**
#      ### 服务名称。Zuul 网关默认整合了 ribbon，ribbon + serverId 实现本地负载均衡方式调用接口
#      serviceId: school-basic-server
#    api-b:
#      path: /api-acs/**
#      serviceId: school-acs-server
