server:
  port: 8500
spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

app:
  ### portal 中新建 Application 的 AppId
  id: zuul_server_config
apollo:
  ### configserver 的地址
  meta: http://${configserver.host}:8080
